import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/page-header";

export const Route = createFileRoute("/_authenticated/admin/notifications")({ component: NotificationsPage });

function NotificationsPage() {
  const { data } = useQuery({
    queryKey: ["notifications"],
    queryFn: async () => {
      const { data, error } = await supabase.from("notifications").select("*").order("created_at", { ascending: false }).limit(200);
      if (error) throw error; return data;
    },
  });

  return (
    <div className="p-8 space-y-6">
      <PageHeader title="Notifications" subtitle="Renewal reminders and other queued messages generated by the system." />
      <Card>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="border-b bg-muted/40 text-left">
              <tr>
                <th className="px-4 py-3 font-medium">Kind</th>
                <th className="px-4 py-3 font-medium">Channel</th>
                <th className="px-4 py-3 font-medium">Recipient</th>
                <th className="px-4 py-3 font-medium">Subject</th>
                <th className="px-4 py-3 font-medium">Status</th>
                <th className="px-4 py-3 font-medium">Created</th>
              </tr>
            </thead>
            <tbody>
              {data?.length === 0 && <tr><td colSpan={6} className="p-12 text-center text-muted-foreground">No notifications yet. The renewal engine runs daily at 06:00 UTC.</td></tr>}
              {data?.map((n: any) => (
                <tr key={n.id} className="border-b last:border-0">
                  <td className="px-4 py-3 font-mono text-xs">{n.kind}</td>
                  <td className="px-4 py-3"><Badge variant="secondary">{n.channel}</Badge></td>
                  <td className="px-4 py-3">{n.recipient_email ?? n.recipient_phone ?? "—"}</td>
                  <td className="px-4 py-3">{n.subject ?? "—"}</td>
                  <td className="px-4 py-3"><Badge variant={n.status === "sent" ? "default" : n.status === "failed" ? "destructive" : "secondary"}>{n.status}</Badge></td>
                  <td className="px-4 py-3 text-xs text-muted-foreground">{new Date(n.created_at).toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}