/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PortalRouteRouteImport } from './routes/_portal/route'
import { Route as PlatformRouteRouteImport } from './routes/_platform/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRenewalsRouteImport } from './routes/_authenticated/renewals'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedClaimsRouteImport } from './routes/_authenticated/claims'
import { Route as PortalPortalIndexRouteImport } from './routes/_portal/portal/index'
import { Route as PlatformPlatformIndexRouteImport } from './routes/_platform/platform/index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as PortalPortalVehiclesRouteImport } from './routes/_portal/portal/vehicles'
import { Route as PortalPortalProfileRouteImport } from './routes/_portal/portal/profile'
import { Route as PortalPortalPoliciesRouteImport } from './routes/_portal/portal/policies'
import { Route as PortalPortalInvoicesRouteImport } from './routes/_portal/portal/invoices'
import { Route as PortalPortalDocumentsRouteImport } from './routes/_portal/portal/documents'
import { Route as PortalPortalClaimsRouteImport } from './routes/_portal/portal/claims'
import { Route as PlatformPlatformNoticesRouteImport } from './routes/_platform/platform/notices'
import { Route as PlatformPlatformAuditRouteImport } from './routes/_platform/platform/audit'
import { Route as PlatformPlatformAgenciesRouteImport } from './routes/_platform/platform/agencies'
import { Route as AuthenticatedPoliciesIdRouteImport } from './routes/_authenticated/policies.$id'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTenantRouteImport } from './routes/_authenticated/admin.tenant'
import { Route as AuthenticatedAdminSessionsRouteImport } from './routes/_authenticated/admin.sessions'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminInsurersRouteImport } from './routes/_authenticated/admin.insurers'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin.emails'
import { Route as AuthenticatedAdminDocsRouteImport } from './routes/_authenticated/admin.docs'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin.branches'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksRenewalRemindersRouteImport } from './routes/api/public/hooks/renewal-reminders'
import { Route as PortalPortalPoliciesIdRouteImport } from './routes/_portal/portal/policies.$id'
import { Route as PortalPortalInvoicesIdRouteImport } from './routes/_portal/portal/invoices.$id'
import { Route as PlatformPlatformAgenciesIdRouteImport } from './routes/_platform/platform/agencies.$id'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRenewalsRoute = AuthenticatedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimsRoute = AuthenticatedClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalPortalIndexRoute = PortalPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PlatformPlatformIndexRoute = PlatformPlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalVehiclesRoute = PortalPortalVehiclesRouteImport.update({
  id: '/portal/vehicles',
  path: '/portal/vehicles',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPortalProfileRoute = PortalPortalProfileRouteImport.update({
  id: '/portal/profile',
  path: '/portal/profile',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPortalPoliciesRoute = PortalPortalPoliciesRouteImport.update({
  id: '/portal/policies',
  path: '/portal/policies',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPortalInvoicesRoute = PortalPortalInvoicesRouteImport.update({
  id: '/portal/invoices',
  path: '/portal/invoices',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPortalDocumentsRoute = PortalPortalDocumentsRouteImport.update({
  id: '/portal/documents',
  path: '/portal/documents',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPortalClaimsRoute = PortalPortalClaimsRouteImport.update({
  id: '/portal/claims',
  path: '/portal/claims',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PlatformPlatformNoticesRoute = PlatformPlatformNoticesRouteImport.update({
  id: '/platform/notices',
  path: '/platform/notices',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformPlatformAuditRoute = PlatformPlatformAuditRouteImport.update({
  id: '/platform/audit',
  path: '/platform/audit',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformPlatformAgenciesRoute =
  PlatformPlatformAgenciesRouteImport.update({
    id: '/platform/agencies',
    path: '/platform/agencies',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const AuthenticatedPoliciesIdRoute = AuthenticatedPoliciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPoliciesRoute,
} as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedInvoicesRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTenantRoute =
  AuthenticatedAdminTenantRouteImport.update({
    id: '/admin/tenant',
    path: '/admin/tenant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSessionsRoute =
  AuthenticatedAdminSessionsRouteImport.update({
    id: '/admin/sessions',
    path: '/admin/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/admin/requests',
    path: '/admin/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInsurersRoute =
  AuthenticatedAdminInsurersRouteImport.update({
    id: '/admin/insurers',
    path: '/admin/insurers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/admin/emails',
    path: '/admin/emails',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDocsRoute = AuthenticatedAdminDocsRouteImport.update({
  id: '/admin/docs',
  path: '/admin/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/admin/branches',
    path: '/admin/branches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRenewalRemindersRoute =
  ApiPublicHooksRenewalRemindersRouteImport.update({
    id: '/api/public/hooks/renewal-reminders',
    path: '/api/public/hooks/renewal-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalPortalPoliciesIdRoute = PortalPortalPoliciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalPortalPoliciesRoute,
} as any)
const PortalPortalInvoicesIdRoute = PortalPortalInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalPortalInvoicesRoute,
} as any)
const PlatformPlatformAgenciesIdRoute =
  PlatformPlatformAgenciesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PlatformPlatformAgenciesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/docs': typeof AuthenticatedAdminDocsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/insurers': typeof AuthenticatedAdminInsurersRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/tenant': typeof AuthenticatedAdminTenantRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/policies/$id': typeof AuthenticatedPoliciesIdRoute
  '/platform/agencies': typeof PlatformPlatformAgenciesRouteWithChildren
  '/platform/audit': typeof PlatformPlatformAuditRoute
  '/platform/notices': typeof PlatformPlatformNoticesRoute
  '/portal/claims': typeof PortalPortalClaimsRoute
  '/portal/documents': typeof PortalPortalDocumentsRoute
  '/portal/invoices': typeof PortalPortalInvoicesRouteWithChildren
  '/portal/policies': typeof PortalPortalPoliciesRouteWithChildren
  '/portal/profile': typeof PortalPortalProfileRoute
  '/portal/vehicles': typeof PortalPortalVehiclesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/platform/': typeof PlatformPlatformIndexRoute
  '/portal/': typeof PortalPortalIndexRoute
  '/platform/agencies/$id': typeof PlatformPlatformAgenciesIdRoute
  '/portal/invoices/$id': typeof PortalPortalInvoicesIdRoute
  '/portal/policies/$id': typeof PortalPortalPoliciesIdRoute
  '/api/public/hooks/renewal-reminders': typeof ApiPublicHooksRenewalRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/docs': typeof AuthenticatedAdminDocsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/insurers': typeof AuthenticatedAdminInsurersRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/tenant': typeof AuthenticatedAdminTenantRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/policies/$id': typeof AuthenticatedPoliciesIdRoute
  '/platform/agencies': typeof PlatformPlatformAgenciesRouteWithChildren
  '/platform/audit': typeof PlatformPlatformAuditRoute
  '/platform/notices': typeof PlatformPlatformNoticesRoute
  '/portal/claims': typeof PortalPortalClaimsRoute
  '/portal/documents': typeof PortalPortalDocumentsRoute
  '/portal/invoices': typeof PortalPortalInvoicesRouteWithChildren
  '/portal/policies': typeof PortalPortalPoliciesRouteWithChildren
  '/portal/profile': typeof PortalPortalProfileRoute
  '/portal/vehicles': typeof PortalPortalVehiclesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/platform': typeof PlatformPlatformIndexRoute
  '/portal': typeof PortalPortalIndexRoute
  '/platform/agencies/$id': typeof PlatformPlatformAgenciesIdRoute
  '/portal/invoices/$id': typeof PortalPortalInvoicesIdRoute
  '/portal/policies/$id': typeof PortalPortalPoliciesIdRoute
  '/api/public/hooks/renewal-reminders': typeof ApiPublicHooksRenewalRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_platform': typeof PlatformRouteRouteWithChildren
  '/_portal': typeof PortalRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/claims': typeof AuthenticatedClaimsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/renewals': typeof AuthenticatedRenewalsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/docs': typeof AuthenticatedAdminDocsRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/insurers': typeof AuthenticatedAdminInsurersRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/_authenticated/admin/tenant': typeof AuthenticatedAdminTenantRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/policies/$id': typeof AuthenticatedPoliciesIdRoute
  '/_platform/platform/agencies': typeof PlatformPlatformAgenciesRouteWithChildren
  '/_platform/platform/audit': typeof PlatformPlatformAuditRoute
  '/_platform/platform/notices': typeof PlatformPlatformNoticesRoute
  '/_portal/portal/claims': typeof PortalPortalClaimsRoute
  '/_portal/portal/documents': typeof PortalPortalDocumentsRoute
  '/_portal/portal/invoices': typeof PortalPortalInvoicesRouteWithChildren
  '/_portal/portal/policies': typeof PortalPortalPoliciesRouteWithChildren
  '/_portal/portal/profile': typeof PortalPortalProfileRoute
  '/_portal/portal/vehicles': typeof PortalPortalVehiclesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_platform/platform/': typeof PlatformPlatformIndexRoute
  '/_portal/portal/': typeof PortalPortalIndexRoute
  '/_platform/platform/agencies/$id': typeof PlatformPlatformAgenciesIdRoute
  '/_portal/portal/invoices/$id': typeof PortalPortalInvoicesIdRoute
  '/_portal/portal/policies/$id': typeof PortalPortalPoliciesIdRoute
  '/api/public/hooks/renewal-reminders': typeof ApiPublicHooksRenewalRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/reset-password'
    | '/unsubscribe'
    | '/claims'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/policies'
    | '/quotations'
    | '/renewals'
    | '/reports'
    | '/vehicles'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/docs'
    | '/admin/emails'
    | '/admin/import'
    | '/admin/insurers'
    | '/admin/notifications'
    | '/admin/requests'
    | '/admin/security'
    | '/admin/sessions'
    | '/admin/tenant'
    | '/admin/users'
    | '/clients/$id'
    | '/invoices/$id'
    | '/policies/$id'
    | '/platform/agencies'
    | '/platform/audit'
    | '/platform/notices'
    | '/portal/claims'
    | '/portal/documents'
    | '/portal/invoices'
    | '/portal/policies'
    | '/portal/profile'
    | '/portal/vehicles'
    | '/lovable/email/suppression'
    | '/platform/'
    | '/portal/'
    | '/platform/agencies/$id'
    | '/portal/invoices/$id'
    | '/portal/policies/$id'
    | '/api/public/hooks/renewal-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/reset-password'
    | '/unsubscribe'
    | '/claims'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/policies'
    | '/quotations'
    | '/renewals'
    | '/reports'
    | '/vehicles'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/docs'
    | '/admin/emails'
    | '/admin/import'
    | '/admin/insurers'
    | '/admin/notifications'
    | '/admin/requests'
    | '/admin/security'
    | '/admin/sessions'
    | '/admin/tenant'
    | '/admin/users'
    | '/clients/$id'
    | '/invoices/$id'
    | '/policies/$id'
    | '/platform/agencies'
    | '/platform/audit'
    | '/platform/notices'
    | '/portal/claims'
    | '/portal/documents'
    | '/portal/invoices'
    | '/portal/policies'
    | '/portal/profile'
    | '/portal/vehicles'
    | '/lovable/email/suppression'
    | '/platform'
    | '/portal'
    | '/platform/agencies/$id'
    | '/portal/invoices/$id'
    | '/portal/policies/$id'
    | '/api/public/hooks/renewal-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_platform'
    | '/_portal'
    | '/onboarding'
    | '/reset-password'
    | '/unsubscribe'
    | '/_authenticated/claims'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/policies'
    | '/_authenticated/quotations'
    | '/_authenticated/renewals'
    | '/_authenticated/reports'
    | '/_authenticated/vehicles'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/docs'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/insurers'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/sessions'
    | '/_authenticated/admin/tenant'
    | '/_authenticated/admin/users'
    | '/_authenticated/clients/$id'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/policies/$id'
    | '/_platform/platform/agencies'
    | '/_platform/platform/audit'
    | '/_platform/platform/notices'
    | '/_portal/portal/claims'
    | '/_portal/portal/documents'
    | '/_portal/portal/invoices'
    | '/_portal/portal/policies'
    | '/_portal/portal/profile'
    | '/_portal/portal/vehicles'
    | '/lovable/email/suppression'
    | '/_platform/platform/'
    | '/_portal/portal/'
    | '/_platform/platform/agencies/$id'
    | '/_portal/portal/invoices/$id'
    | '/_portal/portal/policies/$id'
    | '/api/public/hooks/renewal-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiChatRoute: typeof ApiChatRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksRenewalRemindersRoute: typeof ApiPublicHooksRenewalRemindersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/renewals': {
      id: '/_authenticated/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthenticatedRenewalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims': {
      id: '/_authenticated/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_portal/portal/': {
      id: '/_portal/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalPortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_platform/platform/': {
      id: '/_platform/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformPlatformIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/portal/vehicles': {
      id: '/_portal/portal/vehicles'
      path: '/portal/vehicles'
      fullPath: '/portal/vehicles'
      preLoaderRoute: typeof PortalPortalVehiclesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/portal/profile': {
      id: '/_portal/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalPortalProfileRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/portal/policies': {
      id: '/_portal/portal/policies'
      path: '/portal/policies'
      fullPath: '/portal/policies'
      preLoaderRoute: typeof PortalPortalPoliciesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/portal/invoices': {
      id: '/_portal/portal/invoices'
      path: '/portal/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalPortalInvoicesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/portal/documents': {
      id: '/_portal/portal/documents'
      path: '/portal/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalPortalDocumentsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/portal/claims': {
      id: '/_portal/portal/claims'
      path: '/portal/claims'
      fullPath: '/portal/claims'
      preLoaderRoute: typeof PortalPortalClaimsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_platform/platform/notices': {
      id: '/_platform/platform/notices'
      path: '/platform/notices'
      fullPath: '/platform/notices'
      preLoaderRoute: typeof PlatformPlatformNoticesRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/platform/audit': {
      id: '/_platform/platform/audit'
      path: '/platform/audit'
      fullPath: '/platform/audit'
      preLoaderRoute: typeof PlatformPlatformAuditRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/platform/agencies': {
      id: '/_platform/platform/agencies'
      path: '/platform/agencies'
      fullPath: '/platform/agencies'
      preLoaderRoute: typeof PlatformPlatformAgenciesRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_authenticated/policies/$id': {
      id: '/_authenticated/policies/$id'
      path: '/$id'
      fullPath: '/policies/$id'
      preLoaderRoute: typeof AuthenticatedPoliciesIdRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tenant': {
      id: '/_authenticated/admin/tenant'
      path: '/admin/tenant'
      fullPath: '/admin/tenant'
      preLoaderRoute: typeof AuthenticatedAdminTenantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sessions': {
      id: '/_authenticated/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AuthenticatedAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/insurers': {
      id: '/_authenticated/admin/insurers'
      path: '/admin/insurers'
      fullPath: '/admin/insurers'
      preLoaderRoute: typeof AuthenticatedAdminInsurersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/docs': {
      id: '/_authenticated/admin/docs'
      path: '/admin/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AuthenticatedAdminDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/renewal-reminders': {
      id: '/api/public/hooks/renewal-reminders'
      path: '/api/public/hooks/renewal-reminders'
      fullPath: '/api/public/hooks/renewal-reminders'
      preLoaderRoute: typeof ApiPublicHooksRenewalRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/portal/policies/$id': {
      id: '/_portal/portal/policies/$id'
      path: '/$id'
      fullPath: '/portal/policies/$id'
      preLoaderRoute: typeof PortalPortalPoliciesIdRouteImport
      parentRoute: typeof PortalPortalPoliciesRoute
    }
    '/_portal/portal/invoices/$id': {
      id: '/_portal/portal/invoices/$id'
      path: '/$id'
      fullPath: '/portal/invoices/$id'
      preLoaderRoute: typeof PortalPortalInvoicesIdRouteImport
      parentRoute: typeof PortalPortalInvoicesRoute
    }
    '/_platform/platform/agencies/$id': {
      id: '/_platform/platform/agencies/$id'
      path: '/$id'
      fullPath: '/platform/agencies/$id'
      preLoaderRoute: typeof PlatformPlatformAgenciesIdRouteImport
      parentRoute: typeof PlatformPlatformAgenciesRoute
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedPoliciesRouteChildren {
  AuthenticatedPoliciesIdRoute: typeof AuthenticatedPoliciesIdRoute
}

const AuthenticatedPoliciesRouteChildren: AuthenticatedPoliciesRouteChildren = {
  AuthenticatedPoliciesIdRoute: AuthenticatedPoliciesIdRoute,
}

const AuthenticatedPoliciesRouteWithChildren =
  AuthenticatedPoliciesRoute._addFileChildren(
    AuthenticatedPoliciesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClaimsRoute: typeof AuthenticatedClaimsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRouteWithChildren
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
  AuthenticatedRenewalsRoute: typeof AuthenticatedRenewalsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminDocsRoute: typeof AuthenticatedAdminDocsRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminInsurersRoute: typeof AuthenticatedAdminInsurersRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSessionsRoute: typeof AuthenticatedAdminSessionsRoute
  AuthenticatedAdminTenantRoute: typeof AuthenticatedAdminTenantRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClaimsRoute: AuthenticatedClaimsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRouteWithChildren,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
  AuthenticatedRenewalsRoute: AuthenticatedRenewalsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminDocsRoute: AuthenticatedAdminDocsRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminInsurersRoute: AuthenticatedAdminInsurersRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSessionsRoute: AuthenticatedAdminSessionsRoute,
  AuthenticatedAdminTenantRoute: AuthenticatedAdminTenantRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlatformPlatformAgenciesRouteChildren {
  PlatformPlatformAgenciesIdRoute: typeof PlatformPlatformAgenciesIdRoute
}

const PlatformPlatformAgenciesRouteChildren: PlatformPlatformAgenciesRouteChildren =
  {
    PlatformPlatformAgenciesIdRoute: PlatformPlatformAgenciesIdRoute,
  }

const PlatformPlatformAgenciesRouteWithChildren =
  PlatformPlatformAgenciesRoute._addFileChildren(
    PlatformPlatformAgenciesRouteChildren,
  )

interface PlatformRouteRouteChildren {
  PlatformPlatformAgenciesRoute: typeof PlatformPlatformAgenciesRouteWithChildren
  PlatformPlatformAuditRoute: typeof PlatformPlatformAuditRoute
  PlatformPlatformNoticesRoute: typeof PlatformPlatformNoticesRoute
  PlatformPlatformIndexRoute: typeof PlatformPlatformIndexRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformPlatformAgenciesRoute: PlatformPlatformAgenciesRouteWithChildren,
  PlatformPlatformAuditRoute: PlatformPlatformAuditRoute,
  PlatformPlatformNoticesRoute: PlatformPlatformNoticesRoute,
  PlatformPlatformIndexRoute: PlatformPlatformIndexRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

interface PortalPortalInvoicesRouteChildren {
  PortalPortalInvoicesIdRoute: typeof PortalPortalInvoicesIdRoute
}

const PortalPortalInvoicesRouteChildren: PortalPortalInvoicesRouteChildren = {
  PortalPortalInvoicesIdRoute: PortalPortalInvoicesIdRoute,
}

const PortalPortalInvoicesRouteWithChildren =
  PortalPortalInvoicesRoute._addFileChildren(PortalPortalInvoicesRouteChildren)

interface PortalPortalPoliciesRouteChildren {
  PortalPortalPoliciesIdRoute: typeof PortalPortalPoliciesIdRoute
}

const PortalPortalPoliciesRouteChildren: PortalPortalPoliciesRouteChildren = {
  PortalPortalPoliciesIdRoute: PortalPortalPoliciesIdRoute,
}

const PortalPortalPoliciesRouteWithChildren =
  PortalPortalPoliciesRoute._addFileChildren(PortalPortalPoliciesRouteChildren)

interface PortalRouteRouteChildren {
  PortalPortalClaimsRoute: typeof PortalPortalClaimsRoute
  PortalPortalDocumentsRoute: typeof PortalPortalDocumentsRoute
  PortalPortalInvoicesRoute: typeof PortalPortalInvoicesRouteWithChildren
  PortalPortalPoliciesRoute: typeof PortalPortalPoliciesRouteWithChildren
  PortalPortalProfileRoute: typeof PortalPortalProfileRoute
  PortalPortalVehiclesRoute: typeof PortalPortalVehiclesRoute
  PortalPortalIndexRoute: typeof PortalPortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalPortalClaimsRoute: PortalPortalClaimsRoute,
  PortalPortalDocumentsRoute: PortalPortalDocumentsRoute,
  PortalPortalInvoicesRoute: PortalPortalInvoicesRouteWithChildren,
  PortalPortalPoliciesRoute: PortalPortalPoliciesRouteWithChildren,
  PortalPortalProfileRoute: PortalPortalProfileRoute,
  PortalPortalVehiclesRoute: PortalPortalVehiclesRoute,
  PortalPortalIndexRoute: PortalPortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiChatRoute: ApiChatRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksRenewalRemindersRoute: ApiPublicHooksRenewalRemindersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
