/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRenewalsRouteImport } from './routes/_authenticated/renewals'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedClaimsRouteImport } from './routes/_authenticated/claims'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedPortalVehiclesRouteImport } from './routes/_authenticated/portal/vehicles'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/portal/profile'
import { Route as AuthenticatedPortalPoliciesRouteImport } from './routes/_authenticated/portal/policies'
import { Route as AuthenticatedPortalInvoicesRouteImport } from './routes/_authenticated/portal/invoices'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal/documents'
import { Route as AuthenticatedPortalClaimsRouteImport } from './routes/_authenticated/portal/claims'
import { Route as AuthenticatedPoliciesIdRouteImport } from './routes/_authenticated/policies.$id'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminInsurersRouteImport } from './routes/_authenticated/admin.insurers'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin.emails'
import { Route as AuthenticatedAdminDocsRouteImport } from './routes/_authenticated/admin.docs'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin.branches'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksRenewalRemindersRouteImport } from './routes/api/public/hooks/renewal-reminders'
import { Route as AuthenticatedPortalPoliciesIdRouteImport } from './routes/_authenticated/portal/policies.$id'
import { Route as AuthenticatedPortalInvoicesIdRouteImport } from './routes/_authenticated/portal/invoices.$id'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRenewalsRoute = AuthenticatedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimsRoute = AuthenticatedClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalVehiclesRoute =
  AuthenticatedPortalVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalPoliciesRoute =
  AuthenticatedPortalPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalInvoicesRoute =
  AuthenticatedPortalInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalClaimsRoute =
  AuthenticatedPortalClaimsRouteImport.update({
    id: '/claims',
    path: '/claims',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPoliciesIdRoute = AuthenticatedPoliciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPoliciesRoute,
} as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedInvoicesRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInsurersRoute =
  AuthenticatedAdminInsurersRouteImport.update({
    id: '/admin/insurers',
    path: '/admin/insurers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/admin/emails',
    path: '/admin/emails',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDocsRoute = AuthenticatedAdminDocsRouteImport.update({
  id: '/admin/docs',
  path: '/admin/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/admin/branches',
    path: '/admin/branches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRenewalRemindersRoute =
  ApiPublicHooksRenewalRemindersRouteImport.update({
    id: '/api/public/hooks/renewal-reminders',
    path: '/api/public/hooks/renewal-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalPoliciesIdRoute =
  AuthenticatedPortalPoliciesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalPoliciesRoute,
  } as any)
const AuthenticatedPortalInvoicesIdRoute =
  AuthenticatedPortalInvoicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/claims': typeof AuthenticatedClaimsRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/docs': typeof AuthenticatedAdminDocsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/insurers': typeof AuthenticatedAdminInsurersRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/policies/$id': typeof AuthenticatedPoliciesIdRoute
  '/portal/claims': typeof AuthenticatedPortalClaimsRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRouteWithChildren
  '/portal/policies': typeof AuthenticatedPortalPoliciesRouteWithChildren
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/vehicles': typeof AuthenticatedPortalVehiclesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/portal/invoices/$id': typeof AuthenticatedPortalInvoicesIdRoute
  '/portal/policies/$id': typeof AuthenticatedPortalPoliciesIdRoute
  '/api/public/hooks/renewal-reminders': typeof ApiPublicHooksRenewalRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/docs': typeof AuthenticatedAdminDocsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/insurers': typeof AuthenticatedAdminInsurersRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/policies/$id': typeof AuthenticatedPoliciesIdRoute
  '/portal/claims': typeof AuthenticatedPortalClaimsRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRouteWithChildren
  '/portal/policies': typeof AuthenticatedPortalPoliciesRouteWithChildren
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/vehicles': typeof AuthenticatedPortalVehiclesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/portal/invoices/$id': typeof AuthenticatedPortalInvoicesIdRoute
  '/portal/policies/$id': typeof AuthenticatedPortalPoliciesIdRoute
  '/api/public/hooks/renewal-reminders': typeof ApiPublicHooksRenewalRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/claims': typeof AuthenticatedClaimsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/renewals': typeof AuthenticatedRenewalsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/docs': typeof AuthenticatedAdminDocsRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/insurers': typeof AuthenticatedAdminInsurersRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/policies/$id': typeof AuthenticatedPoliciesIdRoute
  '/_authenticated/portal/claims': typeof AuthenticatedPortalClaimsRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/invoices': typeof AuthenticatedPortalInvoicesRouteWithChildren
  '/_authenticated/portal/policies': typeof AuthenticatedPortalPoliciesRouteWithChildren
  '/_authenticated/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/portal/vehicles': typeof AuthenticatedPortalVehiclesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/portal/invoices/$id': typeof AuthenticatedPortalInvoicesIdRoute
  '/_authenticated/portal/policies/$id': typeof AuthenticatedPortalPoliciesIdRoute
  '/api/public/hooks/renewal-reminders': typeof ApiPublicHooksRenewalRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/unsubscribe'
    | '/portal'
    | '/claims'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/policies'
    | '/quotations'
    | '/renewals'
    | '/reports'
    | '/vehicles'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/docs'
    | '/admin/emails'
    | '/admin/import'
    | '/admin/insurers'
    | '/admin/notifications'
    | '/admin/users'
    | '/clients/$id'
    | '/invoices/$id'
    | '/policies/$id'
    | '/portal/claims'
    | '/portal/documents'
    | '/portal/invoices'
    | '/portal/policies'
    | '/portal/profile'
    | '/portal/vehicles'
    | '/lovable/email/suppression'
    | '/portal/'
    | '/portal/invoices/$id'
    | '/portal/policies/$id'
    | '/api/public/hooks/renewal-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/unsubscribe'
    | '/claims'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/policies'
    | '/quotations'
    | '/renewals'
    | '/reports'
    | '/vehicles'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/docs'
    | '/admin/emails'
    | '/admin/import'
    | '/admin/insurers'
    | '/admin/notifications'
    | '/admin/users'
    | '/clients/$id'
    | '/invoices/$id'
    | '/policies/$id'
    | '/portal/claims'
    | '/portal/documents'
    | '/portal/invoices'
    | '/portal/policies'
    | '/portal/profile'
    | '/portal/vehicles'
    | '/lovable/email/suppression'
    | '/portal'
    | '/portal/invoices/$id'
    | '/portal/policies/$id'
    | '/api/public/hooks/renewal-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/reset-password'
    | '/unsubscribe'
    | '/_authenticated/portal'
    | '/_authenticated/claims'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/policies'
    | '/_authenticated/quotations'
    | '/_authenticated/renewals'
    | '/_authenticated/reports'
    | '/_authenticated/vehicles'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/docs'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/insurers'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/users'
    | '/_authenticated/clients/$id'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/policies/$id'
    | '/_authenticated/portal/claims'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/invoices'
    | '/_authenticated/portal/policies'
    | '/_authenticated/portal/profile'
    | '/_authenticated/portal/vehicles'
    | '/lovable/email/suppression'
    | '/_authenticated/portal/'
    | '/_authenticated/portal/invoices/$id'
    | '/_authenticated/portal/policies/$id'
    | '/api/public/hooks/renewal-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiChatRoute: typeof ApiChatRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksRenewalRemindersRoute: typeof ApiPublicHooksRenewalRemindersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/renewals': {
      id: '/_authenticated/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthenticatedRenewalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims': {
      id: '/_authenticated/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/vehicles': {
      id: '/_authenticated/portal/vehicles'
      path: '/vehicles'
      fullPath: '/portal/vehicles'
      preLoaderRoute: typeof AuthenticatedPortalVehiclesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/profile': {
      id: '/_authenticated/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/policies': {
      id: '/_authenticated/portal/policies'
      path: '/policies'
      fullPath: '/portal/policies'
      preLoaderRoute: typeof AuthenticatedPortalPoliciesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/invoices': {
      id: '/_authenticated/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof AuthenticatedPortalInvoicesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/claims': {
      id: '/_authenticated/portal/claims'
      path: '/claims'
      fullPath: '/portal/claims'
      preLoaderRoute: typeof AuthenticatedPortalClaimsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/policies/$id': {
      id: '/_authenticated/policies/$id'
      path: '/$id'
      fullPath: '/policies/$id'
      preLoaderRoute: typeof AuthenticatedPoliciesIdRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/insurers': {
      id: '/_authenticated/admin/insurers'
      path: '/admin/insurers'
      fullPath: '/admin/insurers'
      preLoaderRoute: typeof AuthenticatedAdminInsurersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/docs': {
      id: '/_authenticated/admin/docs'
      path: '/admin/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AuthenticatedAdminDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/renewal-reminders': {
      id: '/api/public/hooks/renewal-reminders'
      path: '/api/public/hooks/renewal-reminders'
      fullPath: '/api/public/hooks/renewal-reminders'
      preLoaderRoute: typeof ApiPublicHooksRenewalRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/policies/$id': {
      id: '/_authenticated/portal/policies/$id'
      path: '/$id'
      fullPath: '/portal/policies/$id'
      preLoaderRoute: typeof AuthenticatedPortalPoliciesIdRouteImport
      parentRoute: typeof AuthenticatedPortalPoliciesRoute
    }
    '/_authenticated/portal/invoices/$id': {
      id: '/_authenticated/portal/invoices/$id'
      path: '/$id'
      fullPath: '/portal/invoices/$id'
      preLoaderRoute: typeof AuthenticatedPortalInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedPortalInvoicesRoute
    }
  }
}

interface AuthenticatedPortalInvoicesRouteChildren {
  AuthenticatedPortalInvoicesIdRoute: typeof AuthenticatedPortalInvoicesIdRoute
}

const AuthenticatedPortalInvoicesRouteChildren: AuthenticatedPortalInvoicesRouteChildren =
  {
    AuthenticatedPortalInvoicesIdRoute: AuthenticatedPortalInvoicesIdRoute,
  }

const AuthenticatedPortalInvoicesRouteWithChildren =
  AuthenticatedPortalInvoicesRoute._addFileChildren(
    AuthenticatedPortalInvoicesRouteChildren,
  )

interface AuthenticatedPortalPoliciesRouteChildren {
  AuthenticatedPortalPoliciesIdRoute: typeof AuthenticatedPortalPoliciesIdRoute
}

const AuthenticatedPortalPoliciesRouteChildren: AuthenticatedPortalPoliciesRouteChildren =
  {
    AuthenticatedPortalPoliciesIdRoute: AuthenticatedPortalPoliciesIdRoute,
  }

const AuthenticatedPortalPoliciesRouteWithChildren =
  AuthenticatedPortalPoliciesRoute._addFileChildren(
    AuthenticatedPortalPoliciesRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalClaimsRoute: typeof AuthenticatedPortalClaimsRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalInvoicesRoute: typeof AuthenticatedPortalInvoicesRouteWithChildren
  AuthenticatedPortalPoliciesRoute: typeof AuthenticatedPortalPoliciesRouteWithChildren
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalVehiclesRoute: typeof AuthenticatedPortalVehiclesRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalClaimsRoute: AuthenticatedPortalClaimsRoute,
    AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
    AuthenticatedPortalInvoicesRoute:
      AuthenticatedPortalInvoicesRouteWithChildren,
    AuthenticatedPortalPoliciesRoute:
      AuthenticatedPortalPoliciesRouteWithChildren,
    AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
    AuthenticatedPortalVehiclesRoute: AuthenticatedPortalVehiclesRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedPoliciesRouteChildren {
  AuthenticatedPoliciesIdRoute: typeof AuthenticatedPoliciesIdRoute
}

const AuthenticatedPoliciesRouteChildren: AuthenticatedPoliciesRouteChildren = {
  AuthenticatedPoliciesIdRoute: AuthenticatedPoliciesIdRoute,
}

const AuthenticatedPoliciesRouteWithChildren =
  AuthenticatedPoliciesRoute._addFileChildren(
    AuthenticatedPoliciesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
  AuthenticatedClaimsRoute: typeof AuthenticatedClaimsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRouteWithChildren
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
  AuthenticatedRenewalsRoute: typeof AuthenticatedRenewalsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminDocsRoute: typeof AuthenticatedAdminDocsRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminInsurersRoute: typeof AuthenticatedAdminInsurersRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
  AuthenticatedClaimsRoute: AuthenticatedClaimsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRouteWithChildren,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
  AuthenticatedRenewalsRoute: AuthenticatedRenewalsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminDocsRoute: AuthenticatedAdminDocsRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminInsurersRoute: AuthenticatedAdminInsurersRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiChatRoute: ApiChatRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksRenewalRemindersRoute: ApiPublicHooksRenewalRemindersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
